package com.lmlasmo.genegisc.dto;

public enum UserRegisterErro {
	
	USERNAME_USE,
	ALTER_PROFILE_FAILED,
	PASSWORD_CONFIRMED_INCORRECT,
	ALTER_PASSWORD_FAILED,
	REGISTRATION_FAILED,
	DELETION_FAILED

}
